# Generated by Django 3.0.7 on 2020-07-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admZone', '0004_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobno', models.CharField(max_length=50)),
                ('msg', models.CharField(max_length=50)),
                ('dt', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'sms',
            },
        ),
    ]
