# Generated by Django 3.0.7 on 2020-07-16 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admZone', '0007_qpdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qpid', models.CharField(max_length=15)),
                ('question', models.TextField()),
                ('a', models.TextField()),
                ('b', models.TextField()),
                ('c', models.TextField()),
                ('d', models.TextField()),
                ('ans', models.TextField()),
            ],
            options={
                'db_table': 'examquestion',
            },
        ),
    ]
