# Generated by Django 3.0.7 on 2020-07-16 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admZone', '0008_examquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examquestion',
            old_name='qpid',
            new_name='paperid',
        ),
    ]
