# Generated by Django 3.0.7 on 2020-07-16 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admZone', '0009_auto_20200716_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpdetails',
            name='status',
            field=models.TextField(default='false'),
        ),
    ]
