# Generated by Django 3.0.7 on 2020-07-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admZone', '0010_qpdetails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpdetails',
            name='paperid',
            field=models.CharField(default='', max_length=15),
        ),
    ]
