# Generated by Django 3.0.7 on 2020-07-08 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stdZone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='msg',
            new_name='feedback',
        ),
    ]
