# Generated by Django 3.0.7 on 2020-07-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdZone', '0002_auto_20200708_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('question', models.TextField()),
                ('imgname', models.TextField()),
                ('dt', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'question',
            },
        ),
    ]
