# Generated by Django 3.0.7 on 2020-07-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdZone', '0003_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.CharField(max_length=5)),
                ('email', models.CharField(max_length=50)),
                ('question', models.TextField()),
                ('imgname', models.TextField()),
                ('dt', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'answer',
            },
        ),
    ]
