# Generated by Django 3.0.7 on 2020-07-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdZone', '0005_auto_20200712_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('title', models.TextField()),
                ('doc', models.TextField()),
                ('description', models.TextField()),
                ('dt', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'assignment',
            },
        ),
    ]
